### ISSUE TITLE
Fail to Load filebeat JSON index template

### ISSUE THREAD

**Issue by ranjeetranjan** [sadsfae/ansible-elk#23]
TASK [logstash : Load filebeat JSON index template] ***********************************************************************************************************************************************************************
fatal: [192.168.133.163]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://localhost:9200/_template/filebeat?pretty"}

**Comment by ikerib** [comment]
+1

**Comment by lime-red** [comment]
For me, this happened when elasticsearch was still restarting.  By the time we reached the filebeat index task, elasticsearch had not yet had a chance to start listening for the request, so this task fails.

I changed the task to this and had some success:
```
- name: Load filebeat JSON index template
  uri:
    url: http://localhost:9200/_template/filebeat?pretty
    method: POST
    body: "{{ lookup('file', 'filebeat-index-template.json') }}"
    body_format: json
    return_content: yes
  register: statusCode_output
  until: '"json" in statusCode_output and statusCode_output.json.acknowledged == true'
  retries: 30
  delay: 10
```

@sadsfae would you welcome a PR for this?
