### ISSUE TITLE
Add explicit variable file declaration

### ISSUE THREAD

**Issue by knechtionscoding** [sadsfae/ansible-elk#34]
I was doing some work with this playbook and modifying it and discovered that it was erroring out when there were more variable files defined in other places. As such I put in an explicit variable file definition so that ansible took the correct vars file. If you are interested the elk.yml file now looks something like this:
```

- hosts: elk
  remote_user: root
  vars_files:
    - group_vars/elk.yml
  roles:
......

```
This seems like a quality of like upgrade that allows for the vars to be specified individually. Not sure if you want to implement it, but it made my life easier when trying to troubleshoot to explicitly define the vars file instead of trusting ansible.
