### ISSUE TITLE
Refactor into not requiring root to be remote user

### ISSUE THREAD

**Issue by knechtionscoding** [sadsfae/ansible-elk#50]
So I'm moving towards using this without allowing it to be root. I'm working on adding the correct become statements to work without having the server be root@server. Opening issue so we can track the conversation.

**Comment by sadsfae** [comment]
@KnechtionsCoding I think it's a reasonable assumption that you'll need root for the ELK tasks, especially given all the registers and checks in the firewall code and complexity in general.  I'm not against elevation-where-needed here however if it's useful for certain scenarios.

Once ```become: true``` is fanned out It might be easier for people to just adjust this in ```install/elk.yml``` via the ```remote_user:``` directive or even simpler in ```ansible.cfg``` if they need it.

Something like this might work however (haven't tested it) if you wanted it to always use your local user on the remote host (Ansible should default on this anyway).

```
- name: Gathering user info
  local_action: command whoami
  register: youruser

vars:
      remote_user: {{youruser}}

```
