### ISSUE TITLE
Add fluentd option for logging backend

### ISSUE THREAD

**Issue by sadsfae** [sadsfae/ansible-elk#6]
Add an option for fluentd logging backend, with the default to still use elasticsearch like:

```
    - hosts: elk
      remote_user: root
      roles:
        - { role: elasticsearch }
        when: (logging_backend: fluentd)
          - {role: fluentd}
        when: (logging_backend is none)
          - {role: logstash}
        - { role: nginx }
        - { role: kibana }
```
